---
apiVersion: v1
kind: Secret
metadata:
  name: hoplite-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-demo/hoplite-backend-gitops
